### ISSUE TITLE
Have stations linked up properly, but doesn't "charge".

### ISSUE THREAD

**Issue by stfukthnx** [jwvanderbeck/SFCargoTransporter#1]
I have 2 stations created.
In the source station I left it alone.
In the destination station, I set the 1st station is source.
Both stations have power, and have been powered for awhile.
The "charging for transport from..." graph never changes, and I never receive anything out of it.
Latest version of Satisfactory and mod.

**Comment by jwvanderbeck** [comment]
Which mod version please? Just want to confirm when you say "latest" because I just released v0.0.3 a short while ago.

In 0.0.3 the time to charge was increased from 1 minute to 5 minutes so the graph might look like it isn't moving depending no how long you waited?

It's also possible I introduced a bug in the visual display when I changed the timing.  Is the station still actually doing the transport every 5 minutes?

**Comment by stfukthnx** [comment]
Ignore. Stupid problem on my end: Apparently you have to have power going to the power pole you created for them. My dumb mistake.
